# Generated by Django 3.1.5 on 2021-01-21 08:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Messenger", "Messenger"),
                            ("TELEGRAM", "Telegram"),
                            ("Discord", "Discord"),
                            ("Netcat", "Netcat"),
                            ("Line", "Line"),
                            ("Mewe", "Mewe"),
                        ],
                        default="Discord",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=64)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Artificial Intelligence", "Ai"),
                            ("Software Engineering", "Software Engineering"),
                            ("Networking", "Networking"),
                            ("Operating System", "Operating System"),
                            ("Programming Language", "Programming Language"),
                            ("Web and Browser", "Web And Browser"),
                            ("Algorithm", "Algorithm"),
                            ("Hardware", "Hardware"),
                            ("Campus", "Campus"),
                            ("Game", "Game"),
                            ("Animation", "Animation"),
                            ("Common Sense", "Common Sense"),
                            ("CCNS", "Ccns"),
                        ],
                        default="Common Sense",
                        max_length=64,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Eazy", "Eazy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=16,
                    ),
                ),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "wrong_answers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=3
                    ),
                ),
                ("comment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qa_server.player",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qa_server.quiz"
                    ),
                ),
            ],
        ),
    ]
