# Generated by Django 3.1.5 on 2021-01-22 07:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="player",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Messenger", "Messenger"),
                    ("TELEGRAM", "Telegram"),
                    ("Discord", "Discord"),
                    ("Netcat", "Netcat"),
                    ("Line", "Line"),
                    ("Mewe", "Mewe"),
                ],
                default="Discord",
                max_length=16,
            ),
        ),
    ]
