# Generated by Django 3.1.5 on 2021-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_server", "0003_auto_20210122_1411"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provoke",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="player",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Messenger", "Messenger"),
                    ("TELEGRAM", "Telegram"),
                    ("Discord", "Discord"),
                    ("Netcat", "Netcat"),
                    ("Line", "Line"),
                    ("Mewe", "Mewe"),
                ],
                default="Discord",
                max_length=16,
            ),
        ),
    ]
