# Generated by Django 3.1.5 on 2021-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_server", "0005_auto_20210219_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="platform_userid",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="player",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Messenger", "Messenger"),
                    ("Telegram", "Telegram"),
                    ("Discord", "Discord"),
                    ("Netcat", "Netcat"),
                    ("Line", "Line"),
                    ("Mewe", "Mewe"),
                ],
                default="Discord",
                max_length=16,
            ),
        ),
    ]
