# Generated by Django 3.1.5 on 2021-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_server", "0006_auto_20210220_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Messenger", "Messenger"),
                    ("Telegram", "Telegram"),
                    ("Discord", "Discord"),
                    ("Netcat", "Netcat"),
                    ("Line", "Line"),
                    ("Mewe", "Mewe"),
                ],
                default="Discord",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="domain",
            field=models.CharField(
                choices=[
                    ("Artificial Intelligence", "Ai"),
                    ("Software Engineering", "Software Engineering"),
                    ("Networking", "Networking"),
                    ("Operating System", "Operating System"),
                    ("Programming Language", "Programming Language"),
                    ("Web and Browser", "Web And Browser"),
                    ("Algorithm", "Algorithm"),
                    ("Hardware", "Hardware"),
                    ("Campus", "Campus"),
                    ("Game", "Game"),
                    ("Animation", "Animation"),
                    ("Common Sense", "Common Sense"),
                    ("CCNS", "Ccns"),
                    ("Vtuber", "Vtuber"),
                ],
                default="Common Sense",
                max_length=64,
            ),
        ),
    ]
