# Generated by Django 3.1.7 on 2021-04-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_server', '0007_auto_20210224_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='company',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='platform',
            field=models.CharField(choices=[('Messenger', 'Messenger'), ('Telegram', 'Telegram'), ('Discord', 'Discord'), ('Netcat', 'Netcat'), ('Line', 'Line'), ('Mewe', 'Mewe')], default='Discord', max_length=16),
        ),
    ]
