# Generated by Django 3.1.7 on 2021-05-18 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_server', '0011_auto_20210507_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='platform',
            field=models.CharField(choices=[('Messenger', 'Messenger'), ('Telegram', 'Telegram'), ('Discord', 'Discord'), ('Netcat', 'Netcat'), ('Line', 'Line'), ('Mewe', 'Mewe')], default='Discord', max_length=16),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='wrong_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=2),
        ),
    ]
