version: "3"

services:
    postgres:
        image: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${PG_DBNAME}
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
    qa_server:
        image: "rainrainwu/quiz-server:2.0"
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            - DJANGO_DEBUG=False
            - PG_HOST=postgres
            - PG_DBNAME=${PG_DBNAME}
            - PG_USERNAME=${PG_USERNAME}
            - PG_PASSWORD=${PG_PASSWORD}

volumes:
    pgdata:
